name: 'JavaScript Action Template'

description: 'Add description here'

inputs:
  calculate-prerelease-version:
    description: 'Flag indicating whether to calculate a pre-release version rather than a release version.  Accepts: true|false.'
    required: true
  branch-name:
    description: 'The name of the branch the tag is being generated for. Required when calculating the pre-release version.'
    required: false
  tag-prefix:
    description: 'By default the action strips the prefixes off, but any value provided here will be pre-pended to the next calculated version.'
    required: false
  default-release-type:
    description: 'The default release type that should be used when no tags are detected.  Defaults to major.  Accepted values: major|minor|patch'
    required: false
    default: major

outputs:
  VERSION:
    description: 'The calculated version'

runs:
  using: 'node12'
  main: 'dist/index.js'
